export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const ADD_PRODUCT_DETAILS_FAIL = 'ADD_PRODUCT_DETAILS_FAIL';
export const ADD_PRODUCT_DETAILS_REQUEST = 'ADD_PRODUCT_DETAILS_REQUEST';
export const ADD_PRODUCT_DETAILS_SUCCESS = 'ADD_PRODUCT_DETAILS_SUCCESS';

export const DELETE_PRODUCT_DETAILS_REQUEST = 'DELETE_PRODUCT_DETAILS_REQUEST ';
export const DELETE_PRODUCT_DETAILS_SUCCESS = 'DELETE_PRODUCT_DETAILS_SUCCESS';
export const DELETE_PRODUCT_DETAILS_FAIL = 'DELETE_PRODUCT_DETAILS_FAIL';
